[Grand Search]
Name=com.ddeGrandSearch.Translate
Mode=Auto
Priority=1
DBusService=com.ddeGrandSearch.Translate
DBusAddress=/com/ddeGrandSearch/Translate
DBusInterface=com.ddeGrandSearch.Translate.SearchPlugin
InterfaceVersion=1.0
Exec=/usr/lib/x86_64-linux-gnu/dde-grand-search-daemon/plugins/searcher/translate-search-plugin
